### ISSUE TITLE
Parceljs configuration.

### ISSUE THREAD

**Issue by murunwas** [roxiness/routify#71]
I'm trying to use this router with ParcelJs but it's not working, How do I configure it?

**Comment by jakobrosenberg** [comment]
Hi @murunwas 

Have you checked the documentation here?
https://routify.now.sh/docs/install

If you need more specific help, I need some more information on what is not working or a repo I can clone.

**Comment by murunwas** [comment]
I have followed the documentation but I'm getting this error
![image](https://user-images.githubusercontent.com/8838943/73022355-1f249700-3e32-11ea-8c51-97354c109922.png)

**Comment by jakobrosenberg** [comment]
Just pushed a new release. This should be fixed now.

Please let me know if it works.

**Comment by akauppi** [comment]
I'm still getting the error, if using Routify via CLI. https://github.com/sveltech/routify/issues/72

**Comment by jakobrosenberg** [comment]
Should finally be working now.

**Comment by jakobrosenberg** [comment]
This should be solved. If that's not the case, please feel free to reopen or create a new issue.
